Repository openebs/jiva, pull requests merged in 2020-04, with the labels that each got.

#286 fix(jiva): metafile corruption at sync time
  Makefile
  ci/start_init_test.sh
  controller/rest/stats.go
  go.mod
  go.sum
  main.go
  replica/backup.go
  replica/diff_disk.go
  replica/replica.go
  replica/revision_counter.go
  rpc/client.go
  rpc/types.go
Labels: bug, enhancement

#292 chore(jiva): update sparse-tools dependency
  go.mod
  go.sum
Labels: enhancement, pr/needs-review

#293 doc(changelog): add info about latest improvements and bug fixes
  CHANGELOG.md
Labels: pr/needs-review, pr/release-note

#278 feat(replica): run fsync on files & dir after create/remove/rename operation on files
  Makefile
  app/replica.go
  go.sum
  replica/backup.go
  replica/replica.go
  replica/server.go
  types/types.go
Labels: enhancement, pr/hold-merge, pr/release-note, refactor

#291 fix(replica): rm headfile if already exists
  ci/start_init_test.sh
  replica/replica.go
  replica/replica_test.go
Labels: bug, pr/needs-merge

#290 feat(replica): add option to flush log to file
  app/log.go
  app/replica.go
  controller/client/controller_client.go
  controller/rest/model.go
  controller/rest/router.go
  controller/rest/volume.go
  go.mod
  go.sum
  main.go
  replica/client/client.go
  replica/replica.go
  replica/rest/model.go
  replica/rest/replica.go
  replica/rest/router.go
  replica/server.go
  util/util.go
Labels: documentation, enhancement, pr/hold-merge, pr/needs-review, pr/release-note

#295 docs(project): add project specific docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
  MAINTAINERS
  RELEASE.md
  code-standard.md
  developer-setup.md
Labels: documentation

#296 fix(replica): make preload operations of secondary replicas lockless
  app/replica.go
  ci/start_init_test.sh
  error-inject/default.go
  error-inject/inject.go
  replica/backup.go
  replica/client/client.go
  replica/diff_disk.go
  replica/replica.go
  replica/replica_test.go
  replica/rest/model.go
  replica/server.go
  scripts/test
  sync/sync.go
Labels: enhancement, pr/needs-review, pr/release-note

#297 feat(replica): add command to get rebuild estimation
  app/add_replica.go
  app/syncinfo.go
  ci/start_init_test.sh
  main.go
  replica/client/client.go
  replica/rest/model.go
  replica/rest/replica.go
  replica/rest/router.go
  sync/rebuild/progress.go
  sync/sync.go
  types/types.go
  util/util.go
Labels: documentation, enhancement, pr/needs-review, pr/release-note
