Repository openebs/jiva, pull requests merged in 2020-01, with the labels that each got.

#260 fix(replica): optimize rebuild process
  ci/start_init_test.sh
  controller/rebuild.go
  replica/client/client.go
  replica/replica.go
  replica/rest/model.go
  replica/rest/replica.go
  replica/revision_counter.go
  replica/server.go
  sync/sync.go
Labels: enhancement

#261 [WIP] fix(controller): remove wo replica
  controller/control.go
  replica/client/client.go
  sync/sync.go
Labels: enhancement

#263 fix(replica): add replica with greater revision count
  backend/remote/remote.go
  ci/start_init_test.sh
  controller/control.go
  replica/replica.go
  replica/rest/model.go
  replica/rest/replica.go
  replica/server.go
Labels: bug

#264 refact(ci): fix flaky test cases
  ci/start_init_test.sh
  package/Dockerfile_tests
Labels: enhancement

#266 refact(controller): generate url for resize action on volume
  ci/start_init_test.sh
  controller/control.go
  controller/rest/model.go
  controller/rest/volume.go
Labels: enhancement

#267 refactor(gitlab-yaml): Removed the request to trigger pipeline in packet
  .gitlab-ci.yml
Labels: CI
