Repository openebs/jiva, pull requests merged in 2020-03, with the labels that each got.

#275 feat(build): enable auto build for arm64 binaries
  .travis.yml
  Makefile
  ci/start_init_test.sh
  scripts/ci
  scripts/push
Labels: project/hold-review

#280 revert(controller): comment out autosnapdeletion
  app/controller.go
  ci/start_init_test.sh
  controller/control.go
  controller/rebuild.go
Labels: bug

#281 revert(replica): comment revision count related checks at replica
  ci/start_init_test.sh
  sync/sync.go
Labels: bug

#282 cherry-pick(jiva): add latest changes to v1.6.x
  app/controller.go
  ci/start_init_test.sh
  controller/control.go
  controller/rebuild.go
  sync/sync.go
Labels: cherry-pick, release-note

#283 cherry-pick(jiva): add latest changes to v1.7.x
  app/controller.go
  ci/start_init_test.sh
  controller/control.go
  controller/rebuild.go
  sync/sync.go
Labels: cherry-pick, release-note

#284 cherry-pick(jiva): add latest changes to v1.8.x
  app/controller.go
  ci/start_init_test.sh
  controller/control.go
  controller/rebuild.go
  sync/sync.go
Labels: cherry-pick, release-note

#285 fix(replica): update snapshot name in metafile
  replica/replica.go
Labels: bug

#289 fix(replica): print http resp for bad status
  backend/remote/remote.go
Labels: enhancement

#287 fix(replica): get usedlogical size info from healthy replica
  app/snapshot.go
  controller/replicator.go
  controller/rest/model.go
  controller/rest/replica.go
  controller/rest/volume.go
  replica/replica.go
  replica/rest/model.go
  types/types.go
Labels: bug, enhancement, pr/release-note
